use_frameworks!

platform :ios, '10.0'

target 'MyTest_Example' do
  pod 'MyTest', :path => '../'

  target 'MyTest_Tests' do
    inherit! :search_paths

   # pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
